import React from 'react';
import { FiCheckCircle } from 'react-icons/fi';

export default function AccessibilityStatement() {
  return (
    <div style={{ padding: '60px 0' }} className="animate-fade-in">
      <div className="container" style={{ maxWidth: '800px' }}>
        <div className="glass-panel" style={{ padding: '40px', borderRadius: '24px' }}>

          <h1 style={{ fontSize: '32px', fontWeight: '800', marginBottom: '8px' }}>
            Accessibility <span className="text-gradient">Statement</span>
          </h1>
          <p style={{ color: 'var(--text-muted)', fontSize: '12px', marginBottom: '30px' }}>
            Last Updated: June 12, 2026
          </p>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '24px', fontSize: '14px', lineHeight: '1.7', color: 'var(--text-muted)' }}>

            <section>
              <h3 style={{ fontSize: '18px', fontWeight: '800', color: 'var(--text-main)', marginBottom: '10px' }}>
                Our Commitment
              </h3>
              <p>
                All Tool Master is committed to ensuring digital accessibility for people of all abilities. We are continually improving the user experience for everyone and applying the relevant accessibility standards to make our platform as inclusive as possible.
              </p>
            </section>

            <section>
              <h3 style={{ fontSize: '18px', fontWeight: '800', color: 'var(--text-main)', marginBottom: '10px' }}>
                Conformance Status
              </h3>
              <p>
                We aim to conform to the Web Content Accessibility Guidelines (WCAG) 2.1, Level AA. These guidelines explain how to make web content more accessible for people with disabilities and more user-friendly for everyone. While we strive for full compliance, some areas may still be under active improvement.
              </p>
            </section>

            <section>
              <h3 style={{ fontSize: '18px', fontWeight: '800', color: 'var(--text-main)', marginBottom: '12px' }}>
                Accessibility Features
              </h3>
              <p style={{ marginBottom: '12px' }}>
                All Tool Master includes the following accessibility features:
              </p>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                {[
                  'Semantic HTML: We use proper heading hierarchies (H1-H6), landmarks, and semantic elements to ensure screen readers can accurately interpret page structure.',
                  'Keyboard Navigation: All interactive elements (buttons, links, form fields, dropdown menus) are accessible via keyboard navigation using Tab, Enter, and Escape keys.',
                  'Color Contrast: Our dark-themed interface is designed with sufficient color contrast ratios between text and backgrounds to meet WCAG AA standards.',
                  'Responsive Design: The platform is fully responsive and works across all screen sizes — desktop, tablet, and mobile — without loss of content or functionality.',
                  'Alt Text: Images include descriptive alt attributes. Decorative images are marked appropriately to be ignored by screen readers.',
                  'Focus Indicators: Interactive elements display visible focus outlines when navigated via keyboard to help users track their position on the page.',
                  'Form Labels: All form fields include associated labels or aria-labels to ensure screen readers can identify their purpose.',
                  'Error Messages: Form validation errors are displayed clearly with descriptive text, associated with the relevant input fields.'
                ].map((item, i) => (
                  <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: '10px' }}>
                    <FiCheckCircle style={{ color: '#10b981', flexShrink: 0, marginTop: '3px', fontSize: '14px' }} />
                    <span><strong style={{ color: 'var(--text-main)' }}>{item.split(':')[0]}:</strong>{item.split(':').slice(1).join(':')}</span>
                  </div>
                ))}
              </div>
            </section>

            <section>
              <h3 style={{ fontSize: '18px', fontWeight: '800', color: 'var(--text-main)', marginBottom: '10px' }}>
                Known Limitations
              </h3>
              <p style={{ marginBottom: '12px' }}>
                Despite our best efforts, some content may not yet be fully accessible:
              </p>
              <ul style={{ paddingLeft: '20px', display: 'flex', flexDirection: 'column', gap: '6px' }}>
                <li>Some third-party embedded content (such as video players) may not fully conform to accessibility standards.</li>
                <li>PDF files generated by our tools may have limited accessibility tagging. We are working on improving PDF output accessibility.</li>
                <li>Complex interactive tools (such as the Resume Builder with live preview) may present challenges for screen reader users. We are actively improving these experiences.</li>
              </ul>
            </section>

            <section>
              <h3 style={{ fontSize: '18px', fontWeight: '800', color: 'var(--text-main)', marginBottom: '10px' }}>
                Browser & Assistive Technology Compatibility
              </h3>
              <p>
                All Tool Master is designed to be compatible with modern web browsers including Google Chrome, Mozilla Firefox, Microsoft Edge, and Safari. The platform should work with popular assistive technologies including screen readers (NVDA, JAWS, VoiceOver), voice recognition software, and screen magnification tools.
              </p>
            </section>

            <section>
              <h3 style={{ fontSize: '18px', fontWeight: '800', color: 'var(--text-main)', marginBottom: '10px' }}>
                Feedback & Contact
              </h3>
              <p>
                We welcome your feedback on the accessibility of All Tool Master. If you encounter any accessibility barriers or have suggestions for improvement, please contact us:
              </p>
              <div style={{ marginTop: '12px', padding: '16px', borderRadius: '12px', border: '1px solid var(--border-color)', background: 'rgba(0,0,0,0.02)' }}>
                <p style={{ marginBottom: '4px' }}><strong style={{ color: 'var(--text-main)' }}>Email:</strong>{' '}
                  <a href="mailto:vhshah1711@gmail.com" style={{ color: 'var(--accent-color)', textDecoration: 'none', fontWeight: '600' }}>vhshah1711@gmail.com</a>
                </p>
                <p><strong style={{ color: 'var(--text-main)' }}>Contact Page:</strong>{' '}
                  <a href="/contact" style={{ color: 'var(--accent-color)', textDecoration: 'none', fontWeight: '600' }}>alltoolmaster.me/contact</a>
                </p>
              </div>
              <p style={{ marginTop: '12px' }}>
                We try to respond to accessibility feedback within 5 business days and will work to resolve any issues as quickly as possible.
              </p>
            </section>

          </div>
        </div>
      </div>
    </div>
  );
}
